
package pl.lodz.p.it.tks.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserGetSoapServiceImplService", targetNamespace = "http://client.soap.tks.it.p.lodz.pl/", wsdlLocation = "https://raw.githubusercontent.com/pkomuda/tks-lab/master/get.wsdl")
public class UserGetSoapServiceImplService
    extends Service
{

    private final static URL USERGETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERGETSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERGETSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://client.soap.tks.it.p.lodz.pl/", "UserGetSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://raw.githubusercontent.com/pkomuda/tks-lab/master/soap/soapservices/src/main/java/pl/lodz/p/it/tks/soap/services/get.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERGETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERGETSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserGetSoapServiceImplService() {
        super(__getWsdlLocation(), USERGETSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserGetSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERGETSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserGetSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERGETSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserGetSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERGETSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserGetSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserGetSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserGetSoapServiceImpl
     */
    @WebEndpoint(name = "UserGetSoapServiceImplPort")
    public UserGetSoapServiceImpl getUserGetSoapServiceImplPort() {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserGetSoapServiceImplPort"), UserGetSoapServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserGetSoapServiceImpl
     */
    @WebEndpoint(name = "UserGetSoapServiceImplPort")
    public UserGetSoapServiceImpl getUserGetSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserGetSoapServiceImplPort"), UserGetSoapServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERGETSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERGETSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERGETSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
