
package pl.lodz.p.it.tks.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserFilterSoapServiceImplService", targetNamespace = "http://client.soap.tks.it.p.lodz.pl/", wsdlLocation = "https://raw.githubusercontent.com/pkomuda/tks-lab/master/rent-service/soap/soapservices/src/main/java/pl/lodz/p/it/tks/soap/services/filter.wsdl")
public class UserFilterSoapServiceImplService
    extends Service
{

    private final static URL USERFILTERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERFILTERSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERFILTERSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://client.soap.tks.it.p.lodz.pl/", "UserFilterSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://raw.githubusercontent.com/pkomuda/tks-lab/master/rent-service/soap/soapservices/src/main/java/pl/lodz/p/it/tks/soap/services/filter.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERFILTERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERFILTERSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserFilterSoapServiceImplService() {
        super(__getWsdlLocation(), USERFILTERSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserFilterSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERFILTERSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserFilterSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERFILTERSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserFilterSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERFILTERSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserFilterSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserFilterSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserFilterSoapServiceImpl
     */
    @WebEndpoint(name = "UserFilterSoapServiceImplPort")
    public UserFilterSoapServiceImpl getUserFilterSoapServiceImplPort() {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserFilterSoapServiceImplPort"), UserFilterSoapServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserFilterSoapServiceImpl
     */
    @WebEndpoint(name = "UserFilterSoapServiceImplPort")
    public UserFilterSoapServiceImpl getUserFilterSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserFilterSoapServiceImplPort"), UserFilterSoapServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERFILTERSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERFILTERSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERFILTERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
