
package pl.lodz.p.it.tks.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserCrudSoapServiceImplService", targetNamespace = "http://client.soap.tks.it.p.lodz.pl/", wsdlLocation = "https://raw.githubusercontent.com/pkomuda/tks-lab/master/rent-service/soap/soapservices/src/main/java/pl/lodz/p/it/tks/soap/services/crud.wsdl")
public class UserCrudSoapServiceImplService
    extends Service
{

    private final static URL USERCRUDSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERCRUDSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERCRUDSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://client.soap.tks.it.p.lodz.pl/", "UserCrudSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://raw.githubusercontent.com/pkomuda/tks-lab/master/rent-service/soap/soapservices/src/main/java/pl/lodz/p/it/tks/soap/services/crud.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERCRUDSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERCRUDSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserCrudSoapServiceImplService() {
        super(__getWsdlLocation(), USERCRUDSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserCrudSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERCRUDSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserCrudSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERCRUDSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserCrudSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERCRUDSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserCrudSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserCrudSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserCrudSoapServiceImpl
     */
    @WebEndpoint(name = "UserCrudSoapServiceImplPort")
    public UserCrudSoapServiceImpl getUserCrudSoapServiceImplPort() {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserCrudSoapServiceImplPort"), UserCrudSoapServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserCrudSoapServiceImpl
     */
    @WebEndpoint(name = "UserCrudSoapServiceImplPort")
    public UserCrudSoapServiceImpl getUserCrudSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.soap.tks.it.p.lodz.pl/", "UserCrudSoapServiceImplPort"), UserCrudSoapServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERCRUDSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERCRUDSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERCRUDSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
